
package antsystemproyect;


import javax.swing.SpinnerNumberModel;

/**
 *Clase de interfaz para realizar Simulación del programa.
 * @author Jesús
 */
public class VtnaSimulacion extends javax.swing.JFrame {

    /**
     * Creates new form VtnaSimulacion
     */
    public VtnaSimulacion() {
        initComponents();
        
        //Validaciones de los componentes del Spinner.
        
        SpinnerNumberModel ciclosSpn = new SpinnerNumberModel();
        ciclosSpn.setMinimum(0);
        spinnerCiclos.setModel(ciclosSpn);
        SpinnerNumberModel hormigasSpn = new SpinnerNumberModel();
        hormigasSpn.setMinimum(0);
        spinnerHormigasSimulacion.setModel(hormigasSpn);
        SpinnerNumberModel feromonaSpn = new SpinnerNumberModel();
        feromonaSpn.setMinimum(0);
        feromonaSpn.setValue(1);
        spinnerGradoFeromona.setModel(feromonaSpn);
        SpinnerNumberModel visibilidadSpn = new SpinnerNumberModel();
        visibilidadSpn.setMinimum(0);
        visibilidadSpn.setValue(2);
        spinnerVisibilidadCiudades.setModel(visibilidadSpn);
        SpinnerNumberModel evaporacionSpn = new SpinnerNumberModel();
        evaporacionSpn.setMinimum(0);
        evaporacionSpn.setValue(0.5);
        spinnerEvaporaciónSimulación.setModel(evaporacionSpn);
        SpinnerNumberModel ciudadPartidaSpn = new SpinnerNumberModel();
        ciudadPartidaSpn.setMinimum(0);
        spinnerCiudadPartida.setModel(ciudadPartidaSpn);
        SpinnerNumberModel ciudadLlegadaSpn = new SpinnerNumberModel();
        ciudadLlegadaSpn.setMinimum(0);
        spinnerCiudadLlegada.setModel(ciudadLlegadaSpn);
        
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        spinnerCiclos = new javax.swing.JSpinner();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        btnSimular = new javax.swing.JButton();
        btnVtnaSimularVolver = new javax.swing.JButton();
        jLabel11 = new javax.swing.JLabel();
        spinnerHormigasSimulacion = new javax.swing.JSpinner();
        spinnerGradoFeromona = new javax.swing.JSpinner();
        spinnerVisibilidadCiudades = new javax.swing.JSpinner();
        spinnerEvaporaciónSimulación = new javax.swing.JSpinner();
        spinnerCiudadPartida = new javax.swing.JSpinner();
        spinnerCiudadLlegada = new javax.swing.JSpinner();
        jLabel12 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMinimumSize(new java.awt.Dimension(625, 570));
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 20)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(0, 102, 102));
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Simulación");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 10, 190, 50));

        jLabel2.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(0, 153, 102));
        jLabel2.setText("Indica el número de ciclos que deseas realizar:");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 80, 330, 30));

        spinnerCiclos.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                spinnerCiclosStateChanged(evt);
            }
        });
        getContentPane().add(spinnerCiclos, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 80, 120, 30));

        jLabel3.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(0, 153, 102));
        jLabel3.setText("Indica el número de Hormigas que van a participar:");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 130, 360, 20));

        jLabel4.setFont(new java.awt.Font("Segoe UI", 1, 13)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(0, 153, 102));
        jLabel4.setText("Indica los valores para el grado de importancia de la feromona");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 180, 390, 30));

        jLabel5.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(0, 153, 102));
        jLabel5.setText("(Si deseas usar valores por defecto NO ingresar nada por teclado)");
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 200, 390, 30));

        jLabel6.setFont(new java.awt.Font("Segoe UI", 1, 13)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(0, 153, 102));
        jLabel6.setText("Indica los valores para el grado de visibilidad de las ciudades");
        getContentPane().add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 230, 380, 60));

        jLabel7.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(0, 153, 102));
        jLabel7.setText("(Si deseas usar valores por defecto NO ingresar nada por teclado)");
        getContentPane().add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 246, -1, 60));

        jLabel8.setFont(new java.awt.Font("Segoe UI", 1, 13)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(0, 153, 102));
        jLabel8.setText("Indica valores para el factor de evaporación o usar por defecto:");
        getContentPane().add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 310, 390, 20));

        jLabel9.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(0, 153, 102));
        jLabel9.setText("Indica ciudad de llegada:");
        getContentPane().add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 410, 170, 30));

        btnSimular.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btnSimular.setForeground(new java.awt.Color(0, 102, 102));
        btnSimular.setText("Simular");
        btnSimular.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSimularActionPerformed(evt);
            }
        });
        getContentPane().add(btnSimular, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 460, 100, 40));

        btnVtnaSimularVolver.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        btnVtnaSimularVolver.setForeground(new java.awt.Color(0, 102, 102));
        btnVtnaSimularVolver.setText("Volver");
        btnVtnaSimularVolver.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnVtnaSimularVolverActionPerformed(evt);
            }
        });
        getContentPane().add(btnVtnaSimularVolver, new org.netbeans.lib.awtextra.AbsoluteConstraints(510, 480, 80, 30));

        jLabel11.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel11.setForeground(new java.awt.Color(0, 153, 102));
        jLabel11.setText("Indica ciudad de partida:");
        getContentPane().add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 360, 180, 20));

        spinnerHormigasSimulacion.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                spinnerHormigasSimulacionStateChanged(evt);
            }
        });
        getContentPane().add(spinnerHormigasSimulacion, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 130, 120, 30));

        spinnerGradoFeromona.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                spinnerGradoFeromonaStateChanged(evt);
            }
        });
        getContentPane().add(spinnerGradoFeromona, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 190, 120, 30));

        spinnerVisibilidadCiudades.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                spinnerVisibilidadCiudadesStateChanged(evt);
            }
        });
        getContentPane().add(spinnerVisibilidadCiudades, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 250, 120, 30));

        spinnerEvaporaciónSimulación.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                spinnerEvaporaciónSimulaciónStateChanged(evt);
            }
        });
        getContentPane().add(spinnerEvaporaciónSimulación, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 300, 120, 30));

        spinnerCiudadPartida.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                spinnerCiudadPartidaStateChanged(evt);
            }
        });
        getContentPane().add(spinnerCiudadPartida, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 360, 120, 30));

        spinnerCiudadLlegada.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                spinnerCiudadLlegadaStateChanged(evt);
            }
        });
        getContentPane().add(spinnerCiudadLlegada, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 410, 120, 30));

        jLabel12.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenesProyecto/ImagenSimulacion.jpg"))); // NOI18N
        getContentPane().add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 610, 530));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * Botón para devolver al menú principal.
     * @param evt 
     */
    
    private void btnVtnaSimularVolverActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnVtnaSimularVolverActionPerformed
        this.setVisible(false);
        Principal ventana = new Principal();
        ventana.setVisible(true);
    }//GEN-LAST:event_btnVtnaSimularVolverActionPerformed

    /**
     * Botón para iniciar la simulación.
     * @param evt 
     */
    
    private void btnSimularActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSimularActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnSimularActionPerformed

    private void spinnerCiclosStateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_spinnerCiclosStateChanged
        // TODO add your handling code here:
    }//GEN-LAST:event_spinnerCiclosStateChanged

    private void spinnerHormigasSimulacionStateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_spinnerHormigasSimulacionStateChanged
        // TODO add your handling code here:
    }//GEN-LAST:event_spinnerHormigasSimulacionStateChanged

    private void spinnerGradoFeromonaStateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_spinnerGradoFeromonaStateChanged
        // TODO add your handling code here:
    }//GEN-LAST:event_spinnerGradoFeromonaStateChanged

    private void spinnerVisibilidadCiudadesStateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_spinnerVisibilidadCiudadesStateChanged
        // TODO add your handling code here:
    }//GEN-LAST:event_spinnerVisibilidadCiudadesStateChanged

    private void spinnerEvaporaciónSimulaciónStateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_spinnerEvaporaciónSimulaciónStateChanged
        // TODO add your handling code here:
    }//GEN-LAST:event_spinnerEvaporaciónSimulaciónStateChanged

    private void spinnerCiudadPartidaStateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_spinnerCiudadPartidaStateChanged
        // TODO add your handling code here:
    }//GEN-LAST:event_spinnerCiudadPartidaStateChanged

    private void spinnerCiudadLlegadaStateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_spinnerCiudadLlegadaStateChanged
        // TODO add your handling code here:
    }//GEN-LAST:event_spinnerCiudadLlegadaStateChanged

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(VtnaSimulacion.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(VtnaSimulacion.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(VtnaSimulacion.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(VtnaSimulacion.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new VtnaSimulacion().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnSimular;
    private javax.swing.JButton btnVtnaSimularVolver;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JSpinner spinnerCiclos;
    private javax.swing.JSpinner spinnerCiudadLlegada;
    private javax.swing.JSpinner spinnerCiudadPartida;
    private javax.swing.JSpinner spinnerEvaporaciónSimulación;
    private javax.swing.JSpinner spinnerGradoFeromona;
    private javax.swing.JSpinner spinnerHormigasSimulacion;
    private javax.swing.JSpinner spinnerVisibilidadCiudades;
    // End of variables declaration//GEN-END:variables
}
